# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IntegratorPlugin
                                 A QGIS plugin
 Wtyczka umożliwia prezentację danych z serwisów WMS, WMTS, WFS i WCS w postaci warstw w QGIS. Wtyczka wykorzystuje dane z Ewidencji Zbiorów i Usług oraz strony geoportal.gov.pl
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-08-28
        git sha              : $Format:%H$
        copyright            : (C) 2026 by EnviroSolutions Sp. z o.o.
        email                : gis@envirosolutions.pl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QCoreApplication, QSettings, QTranslator
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QDialog, QToolBar
from qgis.core import Qgis, QgsSettings

from .api.add_service import AddOGCService
from .utils import QtCompat, MessageUtils, NetworkManager
from .integrator_uslug_danych_przestrzennych_dialog import IntegratorUslugPrzestrzennychDialog
from .qgis_feed import QgisFeed, QgisFeedDialog
import os.path

from . import PLUGIN_NAME as plugin_name
from . import PLUGIN_VERSION as plugin_version

class IntegratorUslugPrzestrzennych:
    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)
        self.settings = QgsSettings()
        self.message_utils = MessageUtils()
        self.network_manager = NetworkManager()
        self.ogc_service = AddOGCService(self.network_manager)
        self.selected_industry = None
        self.feed = None
        self.setupFeed()
        
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(self.plugin_dir, 'i18n', 'IntegratorUslugPrzestrzennych_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.actions = []
        self.menu = self.tr(u'&EnviroSolutions')

        self.toolbar = self.iface.mainWindow().findChild(QToolBar, 'EnviroSolutions')
        if not self.toolbar:
            self.toolbar = self.iface.addToolBar(u'EnviroSolutions')
            self.toolbar.setObjectName(u'EnviroSolutions')

        self.first_start = None

    def setupFeed(self) -> None:
        if Qgis.QGIS_VERSION_INT < 31000:
            return

        self.selected_industry = self.settings.value('selected_industry')
        show_dialog = self.settings.value('showDialog', True, type=bool)
        if self.selected_industry is None and show_dialog:
            self.selected_industry = self.showBranchSelectionDialog()

        self.feed = QgisFeed(selected_industry=self.selected_industry, plugin_name=plugin_name)
        self.feed.initFeed()

    def showBranchSelectionDialog(self):
        dialog = QgisFeedDialog()
        if QtCompat.execDialog(dialog) != QDialog.Accepted:
            return None

        selected_industry = dialog.comboBox.currentText()
        self.settings.setValue('selected_industry', selected_industry)
        self.settings.setValue('showDialog', False)
        return selected_industry

    def tr(self, message):
        return QCoreApplication.translate('IntegratorUslugPrzestrzennych', message)

    def addAction(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None,
    ):
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)
        return action

    def initGui(self):
        self.dlg = IntegratorUslugPrzestrzennychDialog()
        self.setupDialog()

        icon_path = os.path.join(self.plugin_dir, 'images', 'icon.svg')
        self.addAction(
            icon_path,
            text=self.tr(plugin_name),
            callback=self.run,
            parent=self.iface.mainWindow(),
        )

        self.first_start = True

    def unload(self):
        for action in self.actions:
            self.iface.removePluginMenu(self.tr(u'&EnviroSolutions'), action)
            self.toolbar.removeAction(action)

    def addService(self) -> None:
        if self.dlg.is_table_empty:
            return
        successfully_add = {}
        selected_urls = self.dlg.getSelectedServicesUrls()
        if not selected_urls:
            self.message_utils.pushMessageBoxWarning(
                self.dlg,
                'Ostrzezenie',
                'Nie wybrano zadnej uslugi z listy.'
            )
            return

        selected_service_type = self.dlg.getSelectedServiceType()
        for name, url in selected_urls.items():
            successfully_add[name] = self.ogc_service.addService(url, selected_service_type)

        self.message_utils.pushMessageBoxInfo(self.dlg, 'Informacja', '\n'.join(
            f'Dodano usluge {key}' if value else f'Nie dodano uslugi {key}'
            for key, value in successfully_add.items()
        ))

    def setupDialog(self) -> None:
        self.dlg.add_btn.clicked.connect(self.addService)

    def run(self):
        if self.first_start:
            self.first_start = False
            self.dlg.setWindowTitle('%s %s' % (plugin_name, plugin_version))
            self.dlg.lbl_pluginVersion.setText('%s %s' % (plugin_name, plugin_version))

        self.dlg.show()
        result = QtCompat.execDialog(self.dlg)
        if result:
            pass
